name: Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # Set up the .env file
      - name: Set Up Environment Variables
        run: |
          echo "API_KEY=${{ secrets.PEXEL_API_KEY }}" >> .env

      # Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
